from pydantic import BaseModel, Field


class AgentResponse(BaseModel):
    ai_response: str = Field(
        description="The response generated by the browsing agent."
    )
    user_follow_up_needed: bool = Field(
        description="Flag indicating if more information is needed from the user.",
        default=True,
    )
    task_complete: bool = Field(
        description="Flag indicating if the browsing task is complete.",
        default=False,
    )
    request_handoff: bool = Field(
        description="Flag indicating if the request should be handed over to a different agent.",
        default=False,
    )
