from starter.agentic.state import UdaHubState
from langchain_core.runnables import RunnableConfig
from langchain_core.messages import SystemMessage, AIMessage
from langchain.agents import create_agent
from starter.agentic.mcp_tool_utils import McpToolFilter
from textwrap import dedent
from pydantic import BaseModel, Field


class BrowsingAgentResponse(BaseModel):
    ai_response: str = Field(
        description="The response generated by the browsing agent."
    )
    user_follow_up_needed: bool = Field(
        description="Flag indicating if more information is needed from the user.",
        default=True,
    )
    task_complete: bool = Field(
        description="Flag indicating if the browsing task is complete.",
        default=False,
    )
    request_handoff: bool = Field(
        description="Flag indicating if the request should be handed over to a different agent.",
        default=False,
    )


async def browsing_agent_node(
    state: UdaHubState, config: RunnableConfig
) -> UdaHubState:
    tools = config.get("configurable", {}).get("mcp_tools", [])
    llm = config.get("configurable", {}).get("llm")
    user = state.get("user", {})
    account_id = user.get("account_id", "")
    account_name = user.get("account_name", account_id)
    account_description = user.get("account_description", "")

    browsing_tools = McpToolFilter(tools).by_tags(["browsing", account_id]).get_all()
    system_prompt = dedent(f"""
        You are an agent that assissts to discover the products offererd by {account_name} (account_id={account_id}).
        {account_description}

        Analyze the users requests and answer it to your best ability. 
        You have access to the customers system through tools proovided to you.
        If you need more information to answer the users question, ask the user for it.
        You can browse the customers products, look up details and answer questions about them.
        You cannot perform actions like purchasing, ordering or reserving products. These things need to be done by a different agent.

        Rules:
        - Use the tools instead of the LLMs knowledge to answer questions about the customers products.
        - If you need more information from the user, ask the user for it instead of making assumptions.
        - If you cannot find what the users looking for, say that you are sorry and that you cannot help with this request.
        - If the user askes to do something that is outside of your capabilities, set the 'request_handoff' flag to true in your response.
        - Always ask the user if the request is complete or if they need further assistance. Only if they confirm that they are done, set the 'task_complete' flag to true in your response.
    """)
    agent = create_agent(
        model=llm,
        system_prompt=SystemMessage(system_prompt),
        tools=browsing_tools,
        response_format=BrowsingAgentResponse,
    )
    response = await agent.ainvoke(
        {"messages": state.get("messages", [])}, config={"recursion_limit": 5}
    )
    structured_response: BrowsingAgentResponse = response["structured_response"]

    return {
        "messages": [AIMessage(content=structured_response.ai_response)],
        "has_pending_messages": True,
        "need_user_input": structured_response.user_follow_up_needed,
        "handoff_requested": structured_response.request_handoff,
        "terminate_chat": structured_response.task_complete,
    }
